<?php
$this->headLink()->appendStylesheet($this->basePath('/calendar/lib/main.css'));
$this->headScript()->appendFile($this->basePath('/calendar/lib/main.js'));
?>

<style>
  #calendar {
    max-width: 1100px;
    margin-top: 50px;
  }

  .fc .fc-button-primary {
    background-color: #26a9e1;
    background-color: var(--fc-button-bg-color, #26a9e1);
    border-color: #26a9e1;
    border-color: var(--fc-button-border-color, #26a9e1);
  }
.fc .fc-button-primary:hover {
    background-color: #26a9e1;
    background-color: var(--fc-button-hover-bg-color, #26a9e1);
    border-color: #26a9e1;
    border-color: var(--fc-button-hover-border-color, #26a9e1);
  }
.fc .fc-button-primary:disabled { /* not DRY */
    background-color: #26a9e1;
    background-color: var(--fc-button-bg-color, #26a9e1);
    border-color: #26a9e1;
    border-color: var(--fc-button-border-color, #26a9e1); /* overrides :hover */
  }
.fc .fc-button-primary:not(:disabled):active,
  .fc .fc-button-primary:not(:disabled).fc-button-active {
    background-color: #26a9e1;
    background-color: var(--fc-button-active-bg-color, #26a9e1);
    border-color: #26a9e1;
    border-color: var(--fc-button-active-border-color, #26a9e1);
  }

</style>

<div id='calendar'></div>

    <script>

        document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');

    var calendar = new FullCalendar.Calendar(calendarEl, {
      initialDate: '<?php echo date("Y-m-d"); ?>',
      initialView: 'dayGridMonth',
      headerToolbar: {
        left: 'prev,next today',
        center: 'title',
        right: 'dayGridMonth,timeGridWeek,timeGridDay'
      },
      slotLabelInterval:'00:30:00',
      slotDuration:'00:30:00',
      height: 'auto',
      navLinks: true, // can click day/week names to navigate views
      editable: false,
      selectable: false,
      selectMirror: false,
      nowIndicator: false,
      allDaySlot:false,
      eventClick: function(info) {
        alert('Event: ' + info.event.title+' \nCoordinates: ' + info.jsEvent.pageX + ',' + info.jsEvent.pageY+'\nView: ' + info.view.type);
       
        // change the border color just for fun
       // info.el.style.borderColor = 'red';
      },
      events: [
       {
          title: 'All Day Event',
          start: '<?php echo date("Y-m-d", strtotime(date("Y-m-d H:i:s")."-10 Day")); ?>',
        },
        {
          title: 'Long Event',
          start: '<?php echo date("Y-m-d", strtotime(date("Y-m-d H:i:s")."-1 Day")); ?>',
          end: '<?php echo date("Y-m-d", strtotime(date("Y-m-d H:i:s")."+1 Day")); ?>'
        },
        {
          groupId: 999,
          title: 'Repeating Event',
          start: '<?php echo date("Y-m-09\TH:00:00"); ?>'//'2021-07-09T16:00:00'
        },
        {
          groupId: 999,
          title: 'Repeating Event',
          start: '<?php echo date("Y-m-16\TH:00:00"); ?>'//'2021-07-16T16:00:00'
        },
        {
          title: 'Conference',
          start: '2020-02-11',
          end: '2020-02-13'
        },
        {
          title: 'Meeting',
          start: '<?php echo date("Y-m-d\TH:00:00"); ?>',//'2020-02-12T10:30:00',
          end: '<?php echo date("Y-m-d\T06:00:00", strtotime(date("Y-m-d H:i:s")."+1 Day")); ?>'//'2020-02-12T12:30:00'
        },
        {
          title: 'Lunch',
          start: '<?php echo date("Y-m-d\T09:00:00", strtotime(date("Y-m-d H:i:s")."-5 Day")); ?>'//'2020-02-12T12:00:00'
        },
        {
          title: 'Meeting',
          start: '<?php echo date("Y-m-d\T11:00:00", strtotime(date("Y-m-d H:i:s")."-5 Day")); ?>'//'2020-02-12T14:30:00'
        },
        {
          title: 'Happy Hour',
          start: '<?php echo date("Y-m-d\T13:00:00", strtotime(date("Y-m-d H:i:s")."-5 Day")); ?>'//'2020-02-12T17:30:00'
        },
        {
          title: 'Dinner',
          start: '<?php echo date("Y-m-d\T13:30:00", strtotime(date("Y-m-d H:i:s")."-5 Day")); ?>'//'2020-02-12T20:00:00'
        },
        {
          title: 'Birthday Party',
          start: '<?php echo date("Y-m-d\T14:00:00", strtotime(date("Y-m-d H:i:s")."-5 Day")); ?>'//'2020-02-13T07:00:00'
        },
        {
          title: 'Click for Google',
          url: 'http://google.com/',
          start: '<?php echo date("Y-m-d", strtotime(date("Y-m-d H:i:s")."+3 Day")); ?>'//'2020-02-28'
        }
      ]
    });

    calendar.render();
  });
</script>