<?php
$this->headLink()->appendStylesheet($this->basePath('/calendar/lib/main.css'));
$this->headLink()->appendStylesheet($this->basePath('/calendar/calendar.css'));
$this->headScript()->appendFile($this->basePath('/calendar/lib/main.js'));
?>

<div id='calendar-container'>
    <div id='calendar'></div>
</div>

    <script>

document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');

    var calendar = new FullCalendar.Calendar(calendarEl, {
      height: '100%',
      expandRows: true,
      /*slotMinTime: '08:00',
      slotMaxTime: '20:00',*/
      slotLabelInterval:'00:30:00',
      slotDuration:'00:30:00',
      headerToolbar: {
        left: 'prev,next today',
        center: 'title',
        right: 'dayGridMonth,timeGridWeek,timeGridDay'
      },
      initialView: 'dayGridMonth',
      initialDate: '<?php echo date("Y-m-d"); ?>',
      navLinks: true, // can click day/week names to navigate views
      editable: false,
      selectable: false,
      nowIndicator: false,
      dayMaxEvents: false, // allow "more" link when too many events
      allDaySlot:false,
      eventClick: function(info) {
        alert('Event: ' + info.event.title+' \nCoordinates: ' + info.jsEvent.pageX + ',' + info.jsEvent.pageY+'\nView: ' + info.view.type);
       
        // change the border color just for fun
       // info.el.style.borderColor = 'red';
      },
      events: [
         {
          title: 'All Day Event',
          start: '<?php echo date("Y-m-d", strtotime(date("Y-m-d H:i:s")."-10 Day")); ?>',
        },
        {
          title: 'Long Event',
          start: '<?php echo date("Y-m-d", strtotime(date("Y-m-d H:i:s")."-1 Day")); ?>',
          end: '<?php echo date("Y-m-d", strtotime(date("Y-m-d H:i:s")."+1 Day")); ?>'
        },
        {
          groupId: 999,
          title: 'Repeating Event',
          start: '<?php echo date("Y-m-09\TH:00:00"); ?>'//'2021-07-09T16:00:00'
        },
        {
          groupId: 999,
          title: 'Repeating Event',
          start: '<?php echo date("Y-m-16\TH:00:00"); ?>'//'2021-07-16T16:00:00'
        },
        {
          title: 'Conference',
          start: '2020-02-11',
          end: '2020-02-13'
        },
        {
          title: 'Meeting',
          start: '<?php echo date("Y-m-d\TH:00:00"); ?>',//'2020-02-12T10:30:00',
          end: '<?php echo date("Y-m-d\T06:00:00", strtotime(date("Y-m-d H:i:s")."+1 Day")); ?>'//'2020-02-12T12:30:00'
        },
        {
          title: 'Lunch',
          start: '<?php echo date("Y-m-d\T09:00:00", strtotime(date("Y-m-d H:i:s")."-5 Day")); ?>'//'2020-02-12T12:00:00'
        },
        {
          title: 'Meeting',
          start: '<?php echo date("Y-m-d\T11:00:00", strtotime(date("Y-m-d H:i:s")."-5 Day")); ?>'//'2020-02-12T14:30:00'
        },
        {
          title: 'Happy Hour',
          start: '<?php echo date("Y-m-d\T13:00:00", strtotime(date("Y-m-d H:i:s")."-5 Day")); ?>'//'2020-02-12T17:30:00'
        },
        {
          title: 'Dinner',
          start: '<?php echo date("Y-m-d\T13:30:00", strtotime(date("Y-m-d H:i:s")."-5 Day")); ?>'//'2020-02-12T20:00:00'
        },
        {
          title: 'Birthday Party',
          start: '<?php echo date("Y-m-d\T14:00:00", strtotime(date("Y-m-d H:i:s")."-5 Day")); ?>'//'2020-02-13T07:00:00'
        },
        {
          title: 'Click for Google',
          url: 'http://google.com/',
          start: '<?php echo date("Y-m-d", strtotime(date("Y-m-d H:i:s")."+3 Day")); ?>'//'2020-02-28'
        }
      ]
    });

    calendar.render();
  });
</script>